services:
    a5sys_acl_doctrine_filter.kernel_request_listener:
        class: A5sys\AclDoctrineFilterBundle\Listener\KernelRequestListener
        bind:
            $roles: "%acl_doctrine_filter.no_acl_roles%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
